import type { AnswerValue, CandidateResult, QuestionConsensus, TopicMatch } from '@vk/core';
import { format, getMessages } from '@vk/i18n';

const messages = getMessages();

export type AiPromptInput = {
  electionName: string;
  districtName: string;
  answered: number;
  total: number;
  results: CandidateResult[];
  topics: TopicMatch[];
  important: QuestionConsensus[];
  againstTheGrain: QuestionConsensus[];
};

/** How many parties the summary names before it stops being a summary. */
const TOP_MATCHES = 3;

function percent(value: number): string {
  return `${Math.round(value)} %`;
}

function positionOf(answer: AnswerValue): string {
  const { dashboard } = messages.results;

  if (answer === true) return dashboard.promptAgree;
  if (answer === false) return dashboard.promptDisagree;
  return dashboard.promptNeutral;
}

/**
 * The copyable summary, assembled here in the browser from the same numbers the
 * screen is showing.
 *
 * No model is involved in writing it and nothing is sent anywhere — it is a
 * template over data the page already has. That matters enough to say out loud
 * on the card itself (`promptNote`), because a block of text captioned "for your
 * AI assistant" is otherwise a reasonable thing to assume was generated by one.
 *
 * Every sentence is phrased to avoid Czech's gendered past tense ("mám
 * zodpovězeno", not "odpověděl jsem"), so the summary reads correctly for
 * whoever copies it without the app ever having to ask.
 */
export function buildAiPrompt({
  electionName,
  districtName,
  answered,
  total,
  results,
  topics,
  important,
  againstTheGrain,
}: AiPromptInput): string {
  const { dashboard } = messages.results;
  const sections: string[] = [];

  sections.push(
    format(dashboard.promptIntro, {
      election: electionName,
      district: districtName,
      answered,
      total,
    }),
  );

  const ranked = results
    .filter((result) => result.match.matchPercentage !== undefined)
    .slice(0, TOP_MATCHES);

  if (ranked.length > 0) {
    sections.push(
      [
        dashboard.promptMatches,
        ...ranked.map(
          (result, index) =>
            `${index + 1}. ${result.candidate.name} — ${percent(result.match.matchPercentage ?? 0)}`,
        ),
      ].join('\n'),
    );
  }

  if (topics.length > 0) {
    sections.push(
      [
        dashboard.promptTopics,
        ...topics.map(
          (topic) =>
            `- ${topic.topic}: ${topic.best.candidate.name} (${percent(topic.best.matchPercentage)})`,
        ),
      ].join('\n'),
    );
  }

  if (important.length > 0) {
    sections.push(
      [
        dashboard.promptImportant,
        ...important.map(
          (entry) => `- ${entry.question.statement} — ${positionOf(entry.userAnswer)}`,
        ),
      ].join('\n'),
    );
  }

  if (againstTheGrain.length > 0) {
    sections.push(
      [
        dashboard.promptGrain,
        ...againstTheGrain.map(
          (entry) =>
            `- ${entry.question.statement} — ${positionOf(entry.userAnswer)} (${format(
              dashboard.agreeCount,
              { agreeing: entry.agreeing.length, responded: entry.respondedCount },
            ).toLocaleLowerCase('cs')})`,
        ),
      ].join('\n'),
    );
  }

  sections.push(dashboard.promptAsk);

  return sections.join('\n\n');
}
