import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BASE_THEME_NAME, themes } from '../src/themes/index';
import { themeToCss } from '../src/to-css';

/**
 * Compile every theme to a plain stylesheet.
 *
 * Shipping static CSS (rather than applying themes from JS at runtime) is what
 * lets the server render the right theme immediately — no flash of the default
 * brand before hydration. `themeToDeclarations` remains available for the
 * runtime case, e.g. per-calculator branding from the backend.
 */
const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist', 'themes');
mkdirSync(outDir, { recursive: true });

const banner = '/* Generated by `pnpm --filter @vk/tokens build`. Edit the .theme.ts file. */\n\n';

for (const theme of themes) {
  // Only the base theme claims `:root`, so adding a theme to the bundle never
  // changes the app until something selects it.
  const selector =
    theme.name === BASE_THEME_NAME
      ? `:root, [data-theme='${theme.name}']`
      : `[data-theme='${theme.name}']`;

  const file = join(outDir, `${theme.name}.css`);
  writeFileSync(file, banner + themeToCss(theme, { selector }));
  console.log(`  ${theme.name} -> dist/themes/${theme.name}.css`);
}

console.log(`\nBuilt ${themes.length} theme(s).`);
